# Generated by Django 4.2.3 on 2023-09-29 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='footercart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.CharField(default='', max_length=70)),
                ('para2', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='wishlistheading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('para3', models.CharField(default='', max_length=70)),
                ('para4', models.CharField(default='', max_length=70)),
                ('para5', models.CharField(default='', max_length=70)),
                ('link', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('link5', models.CharField(default='', max_length=70)),
                ('link6', models.CharField(default='', max_length=70)),
                ('link7', models.CharField(default='', max_length=70)),
                ('link8', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='slider2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='slider1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='shop_offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('dropButton', models.CharField(default='', max_length=70)),
                ('dropdown1', models.CharField(default='', max_length=70)),
                ('dropdown2', models.CharField(default='', max_length=70)),
                ('dropdown3', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=70)),
                ('dropdown1', models.CharField(default='', max_length=70)),
                ('dropdown2', models.CharField(default='', max_length=70)),
                ('dropdown3', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Optionwishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('hover_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('hover_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('hover_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Latest_Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='instaPic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ifEmpty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('link', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='handPicked_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('hover_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GetIntoTech',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('para2', models.CharField(default='', max_length=100)),
                ('para3', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='filter_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('hover_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmptyWishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('link', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='discount_offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=70)),
                ('phoneNo', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=170)),
                ('content', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contact_heading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('heading2', models.CharField(default='', max_length=100)),
                ('heading3', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='colunm4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='column3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='column2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='column1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='catogery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('link1', models.CharField(default='', max_length=70)),
                ('link2', models.CharField(default='', max_length=70)),
                ('link3', models.CharField(default='', max_length=70)),
                ('link4', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cartheading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('para2', models.CharField(default='', max_length=70)),
                ('para3', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Product',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('para1', models.CharField(default='', max_length=70)),
        #         ('bg_img', models.ImageField(default='', upload_to='images')),
        #         ('para2', models.CharField(default='', max_length=70)),
        #         ('para3', models.CharField(default='', max_length=70)),
        #         ('para4', models.CharField(default='', max_length=70)),
        #         ('para5', models.CharField(default='', max_length=70)),
        #         ('link', models.CharField(default='', max_length=70)),
        #         ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        migrations.CreateModel(
            name='blogList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('para2', models.CharField(default='', max_length=70)),
                ('link', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('para1', models.CharField(default='', max_length=70)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('fashion', models.CharField(default='', max_length=70)),
                ('para2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='', max_length=70)),
                ('bg_img', models.ImageField(default='', upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(default='', max_length=100)),
                ('heading2', models.CharField(default='', max_length=100)),
                ('heading3', models.CharField(default='', max_length=100)),
                ('para1', models.CharField(default='', max_length=100)),
                ('para2', models.CharField(default='', max_length=100)),
                ('para3', models.CharField(default='', max_length=100)),
                ('para4', models.CharField(default='', max_length=100)),
                ('para5', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(default='', max_length=70)),
                ('heading2', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
