# Generated by Django 4.2.3 on 2023-10-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customer_email_items_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.items'),
        ),
        migrations.AlterField(
            model_name='box',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.handpicked_product'),
        ),
    ]
