# Generated by Django 4.2.3 on 2023-10-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wishlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='product',
            new_name='handPicked_product',
        ),
        migrations.RenameField(
            model_name='wishlists',
            old_name='product',
            new_name='handPicked_product',
        ),
    ]
