# Generated by Django 4.2.3 on 2023-10-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_handpicked_product_box_handpickedproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='handPickedProduct',
        ),
    ]
