# Generated by Django 4.2.3 on 2023-10-15 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_handpickedproduct_wishlists_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlists',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
