# Generated by Django 4.2.3 on 2023-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wishlists_quantity_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartheading',
            name='para1',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='para1',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='optioncart',
            name='para1',
            field=models.FloatField(default=''),
        ),
    ]
