# Generated by Django 4.2.3 on 2023-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_cartheading_para1_alter_items_para1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handpicked_product',
            name='para1',
            field=models.FloatField(default=''),
        ),
    ]
