# Generated by Django 4.2.3 on 2023-12-14 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_alter_handpicked_product_para1'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField(default='')),
                ('total_amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.IntegerField(default=''),
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.handpicked_product')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('region', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, default='', max_length=255)),
                ('town', models.CharField(default='', max_length=255)),
                ('postcode', models.IntegerField(default=1)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('phoneNo', models.IntegerField(default=1)),
                ('OrderNote', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
