# Generated by Django 4.2.3 on 2023-12-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_order_alter_customer_email_alter_customer_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
