# Generated by Django 4.2.3 on 2023-12-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_checkoutaddress_user_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
