# Generated by Django 4.2.3 on 2023-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_checkoutaddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phoneNo',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='postcode',
            field=models.IntegerField(default=''),
        ),
    ]
